version: '2'

services:
    dnsmasq-service:
        build: ./dnsmasq
        container_name: dnsmasq
        privileged: true
        network_mode: host
        cap_add:
            - NET_ADMIN
        ports:
            - 53:53
            - 53:53/udp
        volumes:
            - ./dnsmasq/conf:/etc/dnsconf
        restart: always

    dnsmasq-bogus-service:
        image: andyshinn/dnsmasq:latest
        container_name: dnsmasq-bogus
        privileged: true
        network_mode: host
        cap_add:
            - NET_ADMIN
        ports:
            - 5353:5353
            - 5353:5353/udp
        command: --port=5353 --log-facility=- -A /#/${EXTIP} -A /#/${EXTIP6}
        restart: always
    
    sniproxy-service:
        image: ab77/sniproxy:latest
        container_name: sniproxy
        build:
            context: docker-sniproxy
        privileged: true
        network_mode: host
        cap_add:
            - NET_ADMIN
        ports:
            - 80:80
            - 443:443
            - 9999:9999
        # dns:
        #     - 8.8.8.8
        #     - 8.8.4.4
        volumes:
            - ./docker-sniproxy/sniproxy.conf:/etc/sniproxy.conf
            - ./openvpn:/openvpn
        # restart: always
    
